name: Bug Report
description: File a bug report
title: "fix: "
labels:
  - bug
assignees:
  - darylwright
body:
  - type: markdown
    attributes:
      value: |-
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: summary
    attributes:
      label: Summary
      placeholder: Please describe the bug in detail
    validations:
      required: true
  - type: textarea
    id: other-info
    attributes:
      label: Other Information
      placeholder: >-
        e.g. detailed explanation, stack traces, related issues, suggestions how to fix,
        links for us to have context (StackOverflow, personal fork, etc.)
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: >-
        By submitting this issue, you agree to follow our
        [Code of Conduct](https://github.com/goldenpathtechnologies/hledger-parser/blob/main/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
